---
title: "Introduction"
---

## Summary

### Sensors

-   Passive (Sun energy reflection in EM wave, don't emit EM waves)

    -   Example: human eyes, satellite (e.g. Wk2 sensor summary - WorldView-3)

    -   ❌ Influenced by atmosphere Haze (require atmosphere correction, no haze in outer space due to no atmosphere) and scattering (wavelength (e.g. blue sky and orange sunset)), clouds and weather

    -   ✔️does not disturb the object or area of interest

-   Active (emit and receive EM wave / energy)

    -   Example: radar, x-ray, LiDAR

    -   ✔️ can pass clouds

### Four resolutions

1.  Spatial

    -   the size of the raster grid per pixel (e.g. 20cm or 30m)

    -   Low spatial resolution: fast (short revisit time); High spatial resolution: costly

2.  Spectral

    -   Spectral signature (EM): Objects on Earth have difference wavelengths = Bands

        -   Multi-spectral data / image

        -   Hyperspectral data / image: stack all colour bands

    -   True colour (human eye can see) and false colour (human cant see)

    -   ❌ atmospheric window (atmospheric transmission / opacity, e.g. water vapour, ozone, CO...)

    -   Spectroradiometer

3.  Radiometric

    -   identify differences in light or reflectance, in practice this is the range of possible values.

    -   Increase bit -\> increase possible values

    -   8-bit sensor: 0-255; 11-bit sensor: 0-2047

4.  Temporal

    -   Revisit time of sensor

    -   High resolution / pixel -\> low revisit = low cost and number \[graph\]

Trade off between resolution and time (and cost)

|     | Sentinel |     | Landsat |
|-----|----------|-----|---------|
|     |          |     |         |
|     |          |     |         |
|     |          |     |         |
|     |          |     |         |
|     |          |     |         |
|     |          |     |         |
|     |          |     |         |
|     |          |     |         |
|     |          |     |         |
|     |          |     |         |

: Sentinel and Landsat

### Questions

## Application

## Reflection
