project:
  type: book
  output-dir: docs

book:
  title: "CASA0023_LD"
  author: "Yi-Chien Chen"
  date: "23-01-25"
  chapters:
    - index.qmd
    - intro.qmd
    - 1_intro.qmd
    - 2_portfolio.qmd
    - 3_corrections.qmd
    - 4_policy.qmd
    - 5_GEE.qmd
    - summary.qmd
    - dictionary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

