project:
  type: book
  output-dir: docs

book:
  title: "CASA0023 Learning Diary"
  author: "Yi-Chien Chen"
  #date: "23-01-16"
  navbar:
    logo: "images/casa_logo.jpg"
    collapse: true
    collapse-below: lg
    background: light
    search: true
    right:
      - icon: github
  repo-url: https://github.com/yichienchen99/CASA0023_LD
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - 1_intro.qmd
    - 2_portfolio.qmd
    - 3_corrections.qmd
    - 4_policy.qmd
    - 5_GEE.qmd
    - 6_classification.qmd
    - 7_classification2.qmd
    - 8_temperature.qmd
    - summary.qmd
    - references.qmd
  favicon: "image/favicon.ico"	

bibliography: references.bib

format:
  html:
    theme:
        light: [cosmo, flatly]
        dark: [cosmo, darkly]
    code-link: true
  pdf:
    documentclass: scrbook

editor: visual

