project:
  type: book
  output-dir: docs

book:
  title: "CASA0023_LD"
  author: "Yi-Chien Chen"
  date: "19/01/2023 (updated: `r Sys.Date()`)"
  chapters:
    - index.qmd
    - intro.qmd
    - 1_intro.qmd
    - 2_portfolio.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

