# Preface {.unnumbered}

This website presents the online learning diary for [CASA0023 Remote Sensing Cities and Environments 22/23](https://andrewmaclachlan.github.io/CASA0023/). It contains brief overview of the weekly lectures including summary of key concepts, some practical outputs showing applications and examples of remote sensing techniques, open source applications from web source and literature, and individual reflection on the learnt concepts/techniques.

### About the author

#### Education

Yi-Chien Chen is currently the master student at [CASA, UCL](https://www.ucl.ac.uk/bartlett/casa/bartlett-centre-advanced-spatial-analysis) in the MSc Urban Spatial Science programme 2022/23. She studied urban planning at [BSP, UCL](https://www.ucl.ac.uk/bartlett/planning/bartlett-school-planning) during 2019-2022 and hold a BSc in Urban Planning, Design and Management.

#### Bio

She has some internship experience in architecture industry focusing on architecture design of residential high-rise complexes and one public space project in a mountainous area, in real estate agency doing quantitative market research, and a university career service role conducting a range of duties from data analysis to poster design. In this uni admin role, her fondness for figures and data grows. She was also a voluntary translator for [ArchDaily](https://www.archdaily.com/) as she's interested in architecture and urban design.

Her recent 2-week (but super productive!) work shadowing in summer 2022 with AECOM London office is the most relevant experience to her planning background, gathering information from the policy and qualitatively constructing design guidance and architecture models at neighbourhood level for the local authorities/government. In this experience, she met the GIS team virtually and see the demands on (geospatial) data-oriented planning policy recommendation and interventions.

Email: zcfther\@ucl.ac.uk

[GitHub](https://github.com/yichienchen99)

### In this diary, {.unnumbered}

Each chapter is the content taught in the corresponding week:

1.  Introduction
    -   Remote sensing data intro / sensors / resolutions (using QGIS/SNAP/R)
2.  Sensor - WorldView3
3.  Corrections
    -   Corrections / Enhancements (using R)
4.  Policy
5.  GEE
    -   Filter/reduce/map (using GEE)
6.  Classification
    -   Pixel-based (supervised and unsupervised)
7.  Classification 2
    -   Object-based, sub-pixel, accuracy assessment
8.  Temperature

### In each chapter,

There will be a summary of key concepts learnt in lecture or practical in that week (!= all the contents but those that are more interesting/useful/powerful (personally)).

-   Content summary (outputs from the practical, small code chunks with relevant explanation and flow charts)

-   ::: {.callout-tip style="color: green;" appearance="minimal"}
    = Benefits of data, policy or methods
    :::

-   ::: {.callout-important style="color: red;" appearance="minimal"}
    = Limitations of data, policy or methods
    :::

-   ::: {.callout-note style="color: blue" appearance="minimal"}
    = Potential future development
    :::

-   Questions on data, policy or methods (but mostly on practicals) and answers to them.

A section of applications will follow, focusing on weekly reading but sometimes expanding to wider literature based on interests.

Finally, there will be a personal reflection on the presented content. This section will include what was interesting (to my planning knowledge) and why (e.g. why the content presented this week will be useful in the future).

Happy reading!

~Please\ do\ report\ an\ issue\ if\ something\ is\ wrong/misunderstood\ to\ support\ my\ learning\ process!\ Thanks!~
